sudo: required
services:
    - docker

before_install:
    - docker build -t devashar/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true devashar/react-test npm test 
after_success:
    -  docker build -t devashar/multi-client ./client
    -  docker build -t devashar/multi-nginx ./nginx
    -  docker build -t devashar/multi-server ./server
    -  docker build -t devashar/multi-worker ./worker
    -  docker login -u= "$DOCKER_ID" -p ="$DOCKER_PASSOWRD"
    -  docker push devashar/multi-client
    -  docker push devashar/multi-nginx
    -  docker push devashar/multi-server
    -  docker push devashar/multi-server
    -  docker push devashar/multi-worker
